name: cosmo_clicker
description: "Cosmo Clicker is a simple clicker game where you click to earn dust and buy stars to earn more money."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
